#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc > /dev/null 2>&1
usermod -o -u "$PUID" abc > /dev/null 2>&1

echo "-------------------------------------
GID/UID
-------------------------------------
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------"

chown abc:abc /data
